inherit_from: .rubocop_todo.yml

require:
  - rubocop-katalyst

AllCops:
  Exclude:
    - "Rakefile"
    - "bin/*"
  NewCops: enable
  TargetRubyVersion: 3.1

Gemspec/RequiredRubyVersion:
  Enabled: false
