inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-katalyst

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 4.0
  Exclude:
    # Dummy app (generated Rails boilerplate)
    - spec/dummy/bin/*
    - spec/dummy/config/**/*
    - spec/dummy/db/**/*
    - spec/dummy/tmp/**/*
    - spec/dummy/node_modules/**/*

Rails:
  Enabled: false
