name: Test

on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v6
        with:
          cache: yarn
      - name: Setup
        run: |
          bin/setup
      - name: Test
        run: |
          bin/ci
        env:
          FERRUM_PROCESS_TIMEOUT: 30
      - name: Archive screenshots and logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-failure-outputs
          path: |
            spec/dummy/tmp/screenshots
            spec/dummy/log
